### ISSUE TITLE
G1CopierYoutube bug with YIT starting wih -

### ISSUE THREAD

**Issue by papiche** [papiche/Astroport.ONE#2]
_____ -X49VQgi86E&https://www.youtube.com/watch?v=-X49VQgi86E _____ 81
--- CACHE SEARCH FOR -X49VQgi86E ---
EMPTY.
COPIE : https://www.youtube.com/watch?v=-X49VQgi86E
.... Downloading La_face_cachee_des_tables_de_multiplication-Micmaths.mp4
/usr/local/bin/yt-dlp -f "(bv*[ext=mp4][height<=720]+ba/b[height<=720])" --no-mtime --embed-thumbnail --add-metadata -o "/home/fred/.zen/tmp/yt-dlp/La_face_cachee_des_tables_de_multiplication-Micmaths.%(ext)s" https://www.youtube.com/watch?v=-X49VQgi86E
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 1367 cookies from firefox
[Youtube] -X49VQgi86E: has already been recorded in the archive

No FILE -- TRYING TO RESTORE CACHE FROM TW --
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1098:7)
    at $:/core/modules/commands/render.js:48:24
    at Object.$tw.utils.each ($:/boot/boot.js:146:12)
    at Command.execute ($:/core/modules/commands/render.js:47:13)
    at Commander.executeNextCommand ($:/core/modules/commander.js:107:14)
    at Commander.executeNextCommand ($:/core/modules/commander.js:111:12)
    at Command.callback ($:/core/modules/commander.js:119:13)
    at Command.execute ($:/core/modules/commands/load.js:44:8) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by papiche** [comment]
Use "grep --"
